Kieran/homepage
codinglabsau/moviedeck pull request #9
Opened 2021-03-26 06:37 UTC by kieranLacey

Started populating the homepage view with data from the database using the queries in the home controller.

Started fixing some visual elements of the template of the hero section to more closely resemble the wire-frame

2021-04-01 07:03 UTC, vrodriguero requested changes
Hey Kieran,

All done for your review! A couple of suggestions, but overall you are on the right track

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/CelebController.php
> +        return view('celebs')->with('celebs', $celebs);
Hey Kieran, you are on the right track. 

Just on the return, we usually do like the following:

`return view('celebs', ['celebs' => $celebs])`

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/CelebController.php
> +    public function show(Celeb $id)
For this you are already passing the celebrity on the route, so the name can be `$celeb` as it is the whole object, instead of just the id. 

Laravel will automatically resolve these and will know that the route is the id of the object by default.

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/CelebController.php
> +        return view('single_celeb')->with('celeb', $celeb);
I have checked your routes, and there are no routes named 'single_celeb' that is why is returning empty 😅 .

I have two suggestions:
- name your single celebrity page, by convention we usually use the restfull actions to determine the name of the route. So for this would be something like `'celeb.show'`.
- same suggestion as before to pass the celeb to the view.

Also, thinking about the celebrity, would you not want to show the movies related to that celebrity? If so you would need to add that relationship.

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +
you can remove unused imports and delete the extra line ;D

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +        return view('home')->with('rated', $rated)->with('celebs', $celebs);
Take a look at the comment about passing things to the view ;D on the CelebController.

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +        return view('home')->with('rated', $rated)->with('celebs', $celebs);
Also in regards to the formatting of the code, try to check if your PHP Storm is setting the code style for php from PSR1/PSR2 format. 
<img width="1040" alt="Screen Shot 2021-04-01 at 4 12 25 pm" src="https://user-images.githubusercontent.com/53244381/113251116-0dc3fe00-9305-11eb-982b-f70e81903b30.png">
<img width="1040" alt="Screen Shot 2021-04-01 at 4 12 45 pm" src="https://user-images.githubusercontent.com/53244381/113251150-19afc000-9305-11eb-8340-9d42d3fc5e5e.png">

2021-04-01 07:03 UTC, vrodriguero commented on resources/views/celebs.blade.php
> +                            <span class="text-lg font-medium text-gray-700 ">{{$celeb->name}}</span>
Try to wire this up with the show celeb page ;D 
 Perhaps when you click on the image of the celebrity name you show be redirected to the celebrity page. 

Also, it is good practice to update the logo to link to the homepage, and the nav to link to the celebrities page ;D

2021-04-01 07:03 UTC, vrodriguero commented on resources/views/home.blade.php
> +                            <span class="mx-2 whitespace-nowrap">{{ $rated[0]->movie->year }}</span>
After you changed the controller these references should also be updated.

any references to `$rated` should be changed to `$movies`, and if you want to get the first item you can do it by using `first()` (`$movies->first()`). Also, make sure to delete any references to `->movie` as you are not querying the review anymore.

2021-04-01 07:03 UTC, vrodriguero commented on routes/web.php
> +Route::get('/celebs/{celeb}', [\App\Http\Controllers\CelebController::class, 'show']);
you can name the show celeb route ;D something like `celeb.show`

2021-04-01 07:03 UTC, vrodriguero commented on resources/views/single_celeb.blade.php
> +
Perhaps try to show the info you had on your controller?

2021-04-01 07:03 UTC, vrodriguero commented on resources/views/celebs.blade.php
> +@endsection
Usually it is nice to organise this into directory, so for celeb views (index and show), I would move them to the celebs directory.  

The name for this should also be changed to show.blade.php, but move them first into the directory then change the name ;D

2021-04-01 07:03 UTC, vrodriguero commented on resources/views/vendor/pagination/bootstrap-4.blade.php
> +@endif
Hey Kieran, what are these pagination files? Perhaps delete the ones not being used, leave the ones referring to tailwind ;D

2021-04-01 07:03 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +        return view('home')->with('rated', $rated)->with('celebs', $celebs);
Okay with Jono help, we were able to find something better :D 

To make this more clearer try to query the movie ;D 

```
$movies = Movie::with(['reviews', 'genres'])
            ->get()
            ->map(function ($movie) {
                $movie->average_rating = $movie->reviews->average('rating');
                return $movie;
            })
            ->sortByDesc('average_rating');
```

2021-04-07 23:49 UTC, kieranLacey commented on app/Http/Controllers/CelebController.php
> +        return view('single_celeb')->with('celeb', $celeb);
We already have that relationship I think, there's a table called celeb_movie, we just haven't used it yet. The movies related to the celebrity would be on the celeb.show page, but I haven't built that page yet

2021-04-08 02:50 UTC, vrodriguero requested changes
Hey Kieran,

I have requested a few changes here and I have a couple of requests to make this PR a bit more complete:

- Implement a single celeb page, show celeb info + related movies. 
- On the celebs page: wire each item to the correspondent celeb single page
- In the layout: wire the celebs tab to the celebs page. 

Start with the changes request and then move to the list above. You can prioritise this and do the registration + login afterwards. 

I will merge the main into this branch to make things a bit easier for you.

2021-04-08 02:50 UTC, vrodriguero commented on app/Http/Controllers/CelebController.php
> +        $single_celeb = Celeb::find($celeb);
Okay so here, you are already passing the object as a parameter, which means that Laravel will already fetch the record for you. 

For this reason, you do not need to find the celeb. You can just pass the $celeb to the view.

2021-04-08 02:50 UTC, vrodriguero commented on resources/views/home.blade.php
> +                            <span class="whitespace-nowrap font-normal"> {{$movies[0]->average_rating}} / 10 </span>
You do not need to use the array, this is now a collection of movies, so you can use `first()` to get the first movie :D

See my previous comments for a reference

2021-04-08 02:50 UTC, vrodriguero commented on resources/views/home.blade.php
> +                                {{intdiv($movies[0]->duration,60)}}@if (intdiv($movies[0]->duration,60) > 1)hrs @else hr @endif
The main now has a function to retrieve the movie duration in the correct format, so you do not need this logic here. just` $movies->first()->duration`.

2021-04-08 02:54 UTC, vrodriguero commented on routes/web.php
> +Route::get('/celebs', [\App\Http\Controllers\CelebController::class, 'index'])->name('celebs');
After doing some research, I notice that the best practice is to name this as 'celebs.index'

2021-04-09 01:57 UTC, vrodriguero requested changes
Hey Kieran,

Yes, that is all good with the single celeb page design. 

I made a couple of suggestions regarding some small issues with formatting and the show celeb method :D 

Great job so far! 😄

2021-04-09 01:57 UTC, vrodriguero commented on app/Http/Controllers/CelebController.php
> +                    ->get();
So Kieran, when you are already passing the celeb as an argument you do not need the variable.

Laravel knows that the parameter is a celebrity model, you do not need to call the model again and fetch the record. That will be resolved automatically. 

So for this, you can simplify to:

```
$celeb->with('movies')->get;
```

The `with` will only need array brackets if there is more than one relation. 

Then on the return, you just pass celeb. 

With the code you have implemented here, you are basically passing the same object two times, which means more work for the DB.

So the majority of cases, for the show, update and delete methods you do not fetch the model, just use the one from the request.

2021-04-09 01:57 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +                        ->get();
To make this easier to read, you can give add an empty line between segments and before the return. 

This is the format you should follow in all of your code. Have you set up the PhpStorm to use the format I have suggested, this makes it easier ;D. 

Also, when you passing multiple values to the view, you do not need separate arrays. You can do it like the example below. 

```
public function index()
    {
        $movies = Movie::with(['reviews', 'genres'])
            ->take(4)
            ->get()
            ->map(function ($movie) {
                $movie->average_rating = round($movie->reviews->average('rating'), 1);
                return $movie;
            })
            ->sortByDesc('average_rating');

        $celebs = Celeb::take(4)
            ->get();

        return view('home', [
            'movies' => $movies,
            'celebs' => $celebs
        ]);
    }
```

2021-04-09 01:57 UTC, vrodriguero commented on resources/views/celebs/show.blade.php
> +                    @endforeach
So for this, after you changed the controller as I mentioned, you will loop through the celeb->movies, instead of the titles variable.

2021-04-09 01:57 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +use App;
you do not need the app import here ;D

2021-04-09 01:57 UTC, vrodriguero commented on app/Http/Controllers/HomeController.php
> +                        ->get();
Also too, you do not need the comments before the methods, as the method names and dependencies are pretty self-explanatory. So you can remove it :D

2021-04-09 02:33 UTC, vrodriguero approved these changes
Great Job! 😸

2021-04-09 02:33 UTC, merged